import { Inter } from "next/font/google";
import "./globals.css";
import "../public/alg-logo.png"
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '../public/alg-logo.png',
    apple: '../public/alg-logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/alg-logo.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/alg-logo.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
